### PR TITLE
Updated the three screenshots to be in context using the Macbook mockup.

### LINKED ISSUE #7: Improve screenshots
Maybe add frames to screenshots.

https://mockuphone.com/macbookgrey might be helpful.

### PR DESCRIPTION
**Pull request by brentrobbins**
Fixes #7

### CODE REVIEW

**Comment by rajatgoyal715** [comment]
@brentrobbins Thanks for the contribution but the screenshots look funny as they are taken on Ubuntu and have Macbook frames :smile:

**Comment by rajatgoyal715** [comment]
This issue is meant to change the existing screenshots also (if needed).

**Comment by brentrobbins** [comment]
@rajatgoyal715  Do you want me to use this [Dell mockup](https://mockuphone.com/dell-xps15) instead?

**Comment by rajatgoyal715** [comment]
@brentrobbins Sure, you can do that. :+1: 
But, extension designs have been changed. So, the previous screenshots will not work. In that case, I can also work on this issue, if you have no problem.

**Comment by rajatgoyal715** [comment]
@brentrobbins Thanks for your contribution :smile: Closing this PR as screenshots have been added now.

**Pull request closed without merging**
